### ISSUE TITLE
URGENT - It is not possible to register a new user

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/users-hub-interface#26] opened 2014-04-24 10:35 UTC
URGENT - It is not possible to register a new user

Yesterday I tried to register as a new user with the following e-mail addresses:

angelagonzalezrodriguez.agr@gmail.com
agr@iaa.es

Once registered, when I clicked on the received link to activate my new GLORIA account, it appeared an error screen that I append to this issue. The problem occurs with Firefox, Chrome and IExplorer. I tried copying and pasting the link but the result was the same.

In addition, the second time I tried to register using Firefox (with agr@iaa.es), the button 'Register' did not do anything at all and besides, GLORIA web froze.

![error registro chrome](https://cloud.githubusercontent.com/assets/6812954/2788428/657df36e-cb9b-11e3-9507-d77cc0abb279.jpg)

![error registro iexplorer](https://cloud.githubusercontent.com/assets/6812954/2788431/6e018172-cb9b-11e3-9013-a1264391fa3d.jpg)

**Comment by fserena** [comment] 2014-04-24 11:08
Thank you Angela. Working on it.

**Comment by fserena** [comment] 2014-04-24 11:23
Please Angela, can you try again?

**Comment by angelagonzalez** [comment] 2014-04-24 11:26
Ok voy.

De: Fernando Serena [mailto:notifications@github.com] 
Enviado el: jueves, 24 de abril de 2014 13:24
Para: GLORIA-project/users-hub-interface
CC: angelagonzalez
Asunto: Re: [users-hub-interface] URGENT - It is not possible to register a new user (#26)

Please Angela, can you try again?

**Comment by fserena** [comment] 2014-04-24 16:21
This issue is now fixed. The problem was caused by a previous service deployment on which the REST API changed its name from "GLORIAAPI" to "api". ~100 new user registrations were affected, but they are now progressively registering correctly.

**Closed as completed** 2014-04-24 16:21 UTC
Labels: bug
